controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
task_list:
    path: /tasks
    controller: App\Controller\TaskController::list
app_task_view:
    path: '/task/view/{id}'
    controller: App\Controller\TaskController::view
task_delete:
    path: '/task/list'
    controller: App\Controller\TaskController::delete
    methods: ['GET']

task_update:
    path: '/task/update/{id}'
    controller: App\Controller\TaskController::update